### ISSUE TITLE
Starting inspector on 127.0.0.1:6005 failed: address already in use

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#1023]
Starting inspector on 127.0.0.1:6005 failed: address already in use
[Error - 1:50:33 PM] (node:17324) UnhandledPromiseRejectionWarning: Error: invalid schema, expected mongodb or mongodb+srv
    at module.exports../node_modules/mongodb/lib/url_parser.js.module.exports (c:\Users\stephwe\Repos\vscode-cosmosdb\dist\mongo-languageServer.bundle.js:38191:21)
    at connect (c:\Users\stephwe\Repos\vscode-cosmosdb\dist\mongo-languageServer.bundle.js:36103:3)
    at c:\Users\stephwe\Repos\vscode-cosmosdb\dist\mongo-languageServer.bundle.js:35858:7
    at new Promise (<anonymous>)
    at Function.module.exports../node_modules/mongodb/lib/mongo_client.js.MongoClient.connect (c:\Users\stephwe\Repos\vscode-cosmosdb\dist\mongo-languageServer.bundle.js:35854:12)
    at Object.<anonymous> (c:\Users\stephwe\Repos\vscode-cosmosdb\dist\mongo-languageServer.bundle.js:45660:44)
    at Generator.next (<anonymous>)
    at module.exports../src/mongo/connectToMongoClient.ts.__awaiter (c:\Users\stephwe\Repos\vscode-cosmosdb\dist\mongo-languageServer.bundle.js:45647:71)
    at new Promise (<anonymous>)
    at module.exports../src/mongo/connectToMongoClient.ts.__awaiter (c:\Users\stephwe\Repos\vscode-cosmosdb\dist\mongo-languageServer.bundle.js:45643:12)
[Error - 1:50:33 PM] (node:17324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 1:50:33 PM] (node:17324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by StephenWeatherford** [comment]
No repro
