### ISSUE TITLE
[From marketplace feedback] Support the Cosmos DB Emulator

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-cosmosdb#215]
>Excellent extension. Support for the Azure CosmosDB Emulator would be a useful addition though.

**Comment by tjrobinson** [comment]
Thanks for taking this feedback on board. I would like to be able to use the same tool for both development and production and to be able to connect to the Emulator when developing code locally, all from the same tool.

**Comment by EricJizbaMSFT** [comment]
This might be as easy as attaching with a 'localhost' address. Let's look into for 0.4.0

**Comment by jasonchester** [comment]
Connecting to a graph on the emulator with the default connection string:
>AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw s/Jw==;

 I get the following error in the electron developer console:

`messageService.ts:126 self signed certificate: Error: self signed certificate
	at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
	at emitNone (events.js:86:13)
	at TLSSocket.emit (events.js:188:7)
	at TLSSocket._finishInit (_tls_wrap.js:610:8)
	at TLSWrap.TLSSocket._init.ssl.onhandshakedone (_tls_wrap.js:440:38)
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous) @ mainThreadTreeViews.ts:83
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.resolveErr @ lazyPromise.ts:78
e._receiveOneMessage @ rpcProtocol.ts:68
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
log.ts:165   ERR Please return an array of children.: Error: Please return an array of children.
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:299:343
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:139:729)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:143:568)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:144:866)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:144:383)
    at e.resolveErr (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2588:306)
    at e._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2589:682)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2589:10
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2590:913
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:872)`

**Comment by EricJizbaMSFT** [comment]
@jasonchester Yes we see that error as well. It turns out we'll have to make a few changes to our extension before this scenario is supported (since the emulator uses self-signed certificates).

**Comment by EricJizbaMSFT** [comment]
Closing this issue as we've added support for docdb and mongo emulator.
![attachemulator](https://user-images.githubusercontent.com/11282622/35414766-4c0ee56a-01d8-11e8-8ef6-fb9f398d0ff8.png)

The graph emulator will take a little more work. We'll track that in this issue: https://github.com/Microsoft/vscode-cosmosdb/issues/349
