### ISSUE TITLE
drop database fails

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-cosmosdb#32]
Create a database and collection

![image](https://user-images.githubusercontent.com/1487073/29800638-08ecc6b8-8c20-11e7-9c8c-67a24f31b0b7.png)

right click on the database (in my case `stickersDB`) and choose `drop`
click on `Drop` on the confirmation dialog

Get this in the debug console:

``` console
Unhandled Promise rejection: Request disconnect failed with message: Cannot read property 'Symbol(Symbol.iterator)' of undefined ; Zone: <root> ; Task: setImmediate ; Value: Error: Request disconnect failed with message: Cannot read property 'Symbol(Symbol.iterator)' of undefined
	at new ResponseError (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:421:48)
	at processMessageQueue (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:249:17)
	at Immediate.<anonymous> (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:233:13)
	at ZoneDelegate.invokeTask (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:275:35)
	at Zone.runTask (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:151:47)
	at Immediate.ZoneTask.ZoneTask.cancelFn.invoke (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:345:33)
	at Immediate.data.args.(anonymous function) (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:1359:25)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5) Error: Request disconnect failed with message: Cannot read property 'Symbol(Symbol.iterator)' of undefined
	at new ResponseError (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:421:48)
	at processMessageQueue (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:249:17)
	at Immediate.<anonymous> (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:233:13)
	at ZoneDelegate.invokeTask (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:275:35)
	at Zone.runTask (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:151:47)
	at Immediate.ZoneTask.ZoneTask.cancelFn.invoke (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:345:33)
	at Immediate.data.args.(anonymous function) (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:1359:25)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
Error: Uncaught (in promise): Error: Request disconnect failed with message: Cannot read property 'Symbol(Symbol.iterator)' of undefined
Error: Request disconnect failed with message: Cannot read property 'Symbol(Symbol.iterator)' of undefined
	at new ResponseError (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:421:48)
	at processMessageQueue (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:249:17)
	at Immediate.<anonymous> (/Users/chris/src/vscode-cosmosdb/node_modules/vscode-jsonrpc/lib/main.js:233:13)
	at ZoneDelegate.invokeTask (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:275:35)
	at Zone.runTask (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:151:47)
	at Immediate.ZoneTask.ZoneTask.cancelFn.invoke (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:345:33)
	at Immediate.data.args.(anonymous function) (/Users/chris/.vscode-insiders/extensions/msazurermtools.azurerm-vscode-tools-0.3.6/node_modules/zone.js/dist/zone-node.js:1359:25)
	at runCallback (timers.js:672:20)
```

There may be a timing issue. One time I tried this flow it didn't fail, but i was very slow between operations...

**Comment by EricJizbaMSFT** [comment]
I couldn't repro this, but I pushed an update to ej/allCosmos. There was a missing 'await' which could've been causing a timing issue

**Comment by chrisdias** [comment]
looks like this fixed it.
