### ISSUE TITLE
CodeLens disappears/reappears as you type commands

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#609]
1) New mongo scrapbook
2) type "d"
!) CodeLens disappears/reappears
3) finish typing "db.c1."
!) CodeLens disappears
4) type "f"
!) CodeLens reappears

**Comment by StephenWeatherford** [comment]
#2 may be VsCode's fault.
#3 is caused by an exception in our code

InputMismatchException
_offendingState: 60
_recognizer: mongoParser {_listeners: Array(0), _stateNumber: 60, _errHandler: DefaultErrorStrategy, …}
context: FunctionCallContext
ctx: FunctionCallContext {_parent: CommandContext, invokingState: 49, _start: CommonToken}
expectedTokens: IntervalSet
input: CommonTokenStream {tokens: Array(5), p: 4, fetchedEOF: true, …}
inputStream: CommonTokenStream
offendingState: 60
offendingToken: CommonToken {_line: 1, _charPositionInLine: 6, _channel: 0, …}
recognizer: mongoParser
stack: "Error: 
	at DefaultErrorStrategy.recoverInline (C:\Repos\vscode-cosmosdb\node_modules\antlr4ts\DefaultErrorStrategy.js:425:15)
	at mongoParser.match (C:\Repos\vscode-cosmosdb\node_modules\antlr4ts\Parser.js:143:34)
	at mongoParser.functionCall (C:\Repos\vscode-cosmosdb\out\src\mongo\grammar\mongoParser.js:245:49)
	at mongoParser.command (C:\Repos\vscode-cosmosdb\out\src\mongo\grammar\mongoParser.js:156:38)
	at mongoParser.commands (C:\Repos\vscode-cosmosdb\out\src\mongo\grammar\mongoParser.js:88:42)
	at getAllCommands (C:\Repos\vscode-cosmosdb\out\src\mongo\MongoScrapbook.js:124:68)
	at Object.getAllCommandsFromTextDocument (C:\Repos\vscode-cosmosdb\out\src\mongo\MongoScrapbook.js:64:12)
	at MongoCodeLensProvider.provideCodeLenses (C:\Repos\vscode-cosmosdb\out\src\mongo\services\MongoCodeLensProvider.js:45:45)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:648:549
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:621
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:378)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:584)
	at e.provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:648:503)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:662:944
	at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:661:830)
	at e.$provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:662:906)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:894)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:612)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:682)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:451)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:596:384
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:463
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)"
__proto__: RecognitionException {constructor: }
