### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#659]
1) Type this in connected scrapbook:

db.c1

2) Type "period"
!) 	at DefaultErrorStrategy.recoverInline (C:\Repos\vscode-cosmosdb\node_modules\antlr4ts\DefaultErrorStrategy.js:425:15)
	at mongoParser.match (C:\Repos\vscode-cosmosdb\node_modules\antlr4ts\Parser.js:143:34)
	at mongoParser.functionCall (c:\Repos\vscode-cosmosdb\src\mongo\grammar\mongoParser.ts:323:37)
	at mongoParser.command (c:\Repos\vscode-cosmosdb\src\mongo\grammar\mongoParser.ts:234:14)
	at mongoParser.commands (c:\Repos\vscode-cosmosdb\src\mongo\grammar\mongoParser.ts:165:15)
	at getAllCommands (c:\Repos\vscode-cosmosdb\src\mongo\MongoScrapbook.ts:127:65)
	at getAllCommandsFromTextDocument (c:\Repos\vscode-cosmosdb\src\mongo\MongoScrapbook.ts:70:9)
	at Object.getAllErrorsFromTextDocument (c:\Repos\vscode-cosmosdb\src\mongo\MongoScrapbook.ts:26:17)
	at updateErrorsInActiveScrapbook (c:\Repos\vscode-cosmosdb\src\mongo\registerMongoCommands.ts:208:22)
	at Object.<anonymous> (c:\Repos\vscode-cosmosdb\src\mongo\registerMongoCommands.ts:187:13)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Repos\vscode-cosmosdb\out\src\mongo\registerMongoCommands.js:11:71)
	at Promise (<anonymous>)
	at __awaiter (C:\Repos\vscode-cosmosdb\out\src\mongo\registerMongoCommands.js:7:12)
	at Object.<anonymous> (C:\Repos\vscode-cosmosdb\out\src\mongo\registerMongoCommands.js:180:16)
	at Object.<anonymous> (c:\Repos\vscode-azuretools\ui\src\AzureActionHandler.ts:50:37)
	at Object.<anonymous> (c:\Repos\vscode-azuretools\ui\src\callWithTelemetryAndErrorHandling.ts:35:47)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Repos\vscode-azuretools\ui\out\src\callWithTelemetryAndErrorHandling.js:11:71)
	at Promise (<anonymous>)
	at __awaiter (C:\Repos\vscode-azuretools\ui\out\src\callWithTelemetryAndErrorHandling.js:7:12)
	at Object.callWithTelemetryAndErrorHandling (C:\Repos\vscode-azuretools\ui\out\src\callWithTelemetryAndErrorHandling.js:22:12)
	at AzureActionHandler.<anonymous> (c:\Repos\vscode-azuretools\ui\src\AzureActionHandler.ts:45:26)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Repos\vscode-azuretools\ui\out\src\AzureActionHandler.js:11:71)
	at Promise (<anonymous>)
	at __awaiter (C:\Repos\vscode-azuretools\ui\out\src\AzureActionHandler.js:7:12)
	at __dirname.registerEvent.callback._extensionContext.subscriptions.push.args (c:\Repos\vscode-azuretools\ui\src\AzureActionHandler.ts:44:96)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at e.$acceptModelChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:648:362)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
	at c:\Program Files\Microsoft VS Code\resource

**Comment by StephenWeatherford** [comment]
Fixed by #660
